spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #      show_sql: true  # System.out을 통한 출력
        format_sql: true

logging.level:
  root: info
  org.hibernate.SQL: debug  # By logger -> 로그를 찍는다.
  org.hibernate.type: trace  # 쿼리 파라미터를 로그로 찍는다.
